application: luis-ana
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: home.app

- url: /about
  script: about.app

- url: /rsvp
  script: rsvp.app

- url: /location
  script: location.app

- url: /directions
  script: directions.app

- url: /res
  static_dir: res