application: luis-ana
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(es)?
  script: home.app

- url: /about(/es)?
  script: about.app

- url: /rsvp(/es)?
  script: rsvp.app

- url: /location(/es)?
  script: location.app

- url: /directions(/es)?
  script: directions.app

- url: /xxx
  script: xxx.app

- url: /res
  static_dir: res

# All other URLs use the WSGI application named in "app" in not_found.py.
- url: /.*
  script: home.app

libraries:
- name: webapp2
  version: latest